//
//  HMToonBGStyleKit.m
//  Homage App
//
//  Created by Aviv Wolf on 10/23/14.
//  Copyright (c) 2014 Homage. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "HMToonBGStyleKit.h"


@implementation HMToonBGStyleKit

#pragma mark Cache

static UIColor* _fill = nil;
static UIColor* _stroke = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _fill = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
    _stroke = [UIColor colorWithRed: 0.596 green: 0.2 blue: 0.176 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)fill { return _fill; }
+ (UIColor*)stroke { return _stroke; }

#pragma mark Drawing Methods

+ (void)drawCanvas1WithMonsterPosition: (CGFloat)monsterPosition monsterRoarFraction: (CGFloat)monsterRoarFraction;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat monsterJawTop = monsterRoarFraction * 10;
    CGFloat monsterJawBottom = -monsterRoarFraction * 13;
    CGFloat tongue = monsterRoarFraction * 0.2 + 1;

    //// background Drawing
    UIBezierPath* backgroundPath = UIBezierPath.bezierPath;
    [backgroundPath moveToPoint: CGPointMake(0, 568)];
    [backgroundPath addLineToPoint: CGPointMake(320, 568)];
    [backgroundPath addLineToPoint: CGPointMake(320, 0)];
    [backgroundPath addLineToPoint: CGPointMake(0, 0)];
    [backgroundPath addLineToPoint: CGPointMake(0, 568)];
    [backgroundPath closePath];
    [HMToonBGStyleKit.fill setFill];
    [backgroundPath fill];


    //// Loggia Building
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 139.35, 492.31);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 39 Drawing
        UIBezierPath* bezier39Path = UIBezierPath.bezierPath;
        [bezier39Path moveToPoint: CGPointMake(172.92, 31.64)];
        [bezier39Path addLineToPoint: CGPointMake(192.59, 21.18)];
        [bezier39Path addLineToPoint: CGPointMake(232.41, 0)];
        [bezier39Path addLineToPoint: CGPointMake(272.23, 21.18)];
        [bezier39Path addLineToPoint: CGPointMake(291.91, 31.64)];
        bezier39Path.lineCapStyle = kCGLineCapRound;

        bezier39Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier39Path.lineWidth = 5;
        [bezier39Path stroke];


        //// Bezier 41 Drawing
        UIBezierPath* bezier41Path = UIBezierPath.bezierPath;
        [bezier41Path moveToPoint: CGPointMake(172.92, 31.64)];
        [bezier41Path addLineToPoint: CGPointMake(82.26, 31.67)];
        [bezier41Path addLineToPoint: CGPointMake(82.26, 121.3)];
        [bezier41Path addLineToPoint: CGPointMake(0, 121.3)];
        bezier41Path.lineCapStyle = kCGLineCapRound;

        bezier41Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier41Path.lineWidth = 5;
        [bezier41Path stroke];


        //// Bezier 43 Drawing
        UIBezierPath* bezier43Path = UIBezierPath.bezierPath;
        [bezier43Path moveToPoint: CGPointMake(356.69, 31.67)];
        [bezier43Path addLineToPoint: CGPointMake(291.91, 31.64)];
        bezier43Path.lineCapStyle = kCGLineCapRound;

        bezier43Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier43Path.lineWidth = 5;
        [bezier43Path stroke];


        //// Bezier 45 Drawing
        UIBezierPath* bezier45Path = UIBezierPath.bezierPath;
        [bezier45Path moveToPoint: CGPointMake(257.7, 52.08)];
        [bezier45Path addLineToPoint: CGPointMake(257.7, 119.38)];
        bezier45Path.lineCapStyle = kCGLineCapRound;

        bezier45Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier45Path.lineWidth = 5;
        [bezier45Path stroke];


        //// Bezier 47 Drawing
        UIBezierPath* bezier47Path = UIBezierPath.bezierPath;
        [bezier47Path moveToPoint: CGPointMake(291.61, 52.08)];
        [bezier47Path addLineToPoint: CGPointMake(291.61, 119.38)];
        bezier47Path.lineCapStyle = kCGLineCapRound;

        bezier47Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier47Path.lineWidth = 5;
        [bezier47Path stroke];


        //// Bezier 49 Drawing
        UIBezierPath* bezier49Path = UIBezierPath.bezierPath;
        [bezier49Path moveToPoint: CGPointMake(223.79, 52.08)];
        [bezier49Path addLineToPoint: CGPointMake(223.79, 119.38)];
        bezier49Path.lineCapStyle = kCGLineCapRound;

        bezier49Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier49Path.lineWidth = 5;
        [bezier49Path stroke];


        //// Bezier 51 Drawing
        UIBezierPath* bezier51Path = UIBezierPath.bezierPath;
        [bezier51Path moveToPoint: CGPointMake(240.74, 52.08)];
        [bezier51Path addLineToPoint: CGPointMake(240.74, 119.38)];
        bezier51Path.lineCapStyle = kCGLineCapRound;

        bezier51Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier51Path.lineWidth = 5;
        [bezier51Path stroke];


        //// Bezier 53 Drawing
        UIBezierPath* bezier53Path = UIBezierPath.bezierPath;
        [bezier53Path moveToPoint: CGPointMake(274.65, 52.08)];
        [bezier53Path addLineToPoint: CGPointMake(274.65, 119.38)];
        bezier53Path.lineCapStyle = kCGLineCapRound;

        bezier53Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier53Path.lineWidth = 5;
        [bezier53Path stroke];


        //// Bezier 55 Drawing
        UIBezierPath* bezier55Path = UIBezierPath.bezierPath;
        [bezier55Path moveToPoint: CGPointMake(206.83, 52.08)];
        [bezier55Path addLineToPoint: CGPointMake(206.83, 119.38)];
        bezier55Path.lineCapStyle = kCGLineCapRound;

        bezier55Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier55Path.lineWidth = 5;
        [bezier55Path stroke];


        //// Bezier 57 Drawing
        UIBezierPath* bezier57Path = UIBezierPath.bezierPath;
        [bezier57Path moveToPoint: CGPointMake(189.87, 52.08)];
        [bezier57Path addLineToPoint: CGPointMake(189.87, 119.38)];
        bezier57Path.lineCapStyle = kCGLineCapRound;

        bezier57Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier57Path.lineWidth = 5;
        [bezier57Path stroke];


        //// Bezier 59 Drawing
        UIBezierPath* bezier59Path = UIBezierPath.bezierPath;
        [bezier59Path moveToPoint: CGPointMake(172.92, 52.08)];
        [bezier59Path addLineToPoint: CGPointMake(172.92, 119.38)];
        bezier59Path.lineCapStyle = kCGLineCapRound;

        bezier59Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier59Path.lineWidth = 5;
        [bezier59Path stroke];


        //// Bezier 61 Drawing
        UIBezierPath* bezier61Path = UIBezierPath.bezierPath;
        [bezier61Path moveToPoint: CGPointMake(291.61, 52.08)];
        [bezier61Path addLineToPoint: CGPointMake(291.61, 34.72)];
        [bezier61Path addLineToPoint: CGPointMake(173.14, 34.72)];
        [bezier61Path addLineToPoint: CGPointMake(173.14, 52.08)];
        bezier61Path.lineCapStyle = kCGLineCapRound;

        bezier61Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier61Path.lineWidth = 5;
        [bezier61Path stroke];


        //// Rectangle 2 Drawing
        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(144.66, 63.86, 14.01, 43.1)];
        [HMToonBGStyleKit.stroke setStroke];
        rectangle2Path.lineWidth = 5;
        [rectangle2Path stroke];


        //// Rectangle 4 Drawing
        UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(120.3, 64.31, 14.01, 42.39)];
        [HMToonBGStyleKit.stroke setStroke];
        rectangle4Path.lineWidth = 5;
        [rectangle4Path stroke];


        //// Rectangle 6 Drawing
        UIBezierPath* rectangle6Path = [UIBezierPath bezierPathWithRect: CGRectMake(97.27, 64.31, 14.01, 42.39)];
        [HMToonBGStyleKit.stroke setStroke];
        rectangle6Path.lineWidth = 5;
        [rectangle6Path stroke];


        //// Rectangle 8 Drawing
        UIBezierPath* rectangle8Path = [UIBezierPath bezierPathWithRect: CGRectMake(330.22, 63.86, 14.01, 43.1)];
        [HMToonBGStyleKit.stroke setStroke];
        rectangle8Path.lineWidth = 5;
        [rectangle8Path stroke];


        //// Rectangle 10 Drawing
        UIBezierPath* rectangle10Path = [UIBezierPath bezierPathWithRect: CGRectMake(305.87, 64.31, 14.01, 42.39)];
        [HMToonBGStyleKit.stroke setStroke];
        rectangle10Path.lineWidth = 5;
        [rectangle10Path stroke];


        //// Bezier 63 Drawing
        UIBezierPath* bezier63Path = UIBezierPath.bezierPath;
        [bezier63Path moveToPoint: CGPointMake(82.26, 52.08)];
        [bezier63Path addLineToPoint: CGPointMake(356.69, 52.08)];
        bezier63Path.lineCapStyle = kCGLineCapRound;

        bezier63Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier63Path.lineWidth = 5;
        [bezier63Path stroke];



        CGContextRestoreGState(context);
    }


    //// Volcano
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 129.02, 424.42);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 19 Drawing
        UIBezierPath* bezier19Path = UIBezierPath.bezierPath;
        [bezier19Path moveToPoint: CGPointMake(172.69, 49.9)];
        [bezier19Path addCurveToPoint: CGPointMake(161.81, 67.83) controlPoint1: CGPointMake(166.22, 53.27) controlPoint2: CGPointMake(161.81, 60.03)];
        [bezier19Path addLineToPoint: CGPointMake(161.81, 97.77)];
        [bezier19Path addCurveToPoint: CGPointMake(141.61, 117.96) controlPoint1: CGPointMake(161.81, 108.92) controlPoint2: CGPointMake(152.77, 117.96)];
        [bezier19Path addCurveToPoint: CGPointMake(121.42, 97.77) controlPoint1: CGPointMake(130.46, 117.96) controlPoint2: CGPointMake(121.42, 108.92)];
        [bezier19Path addLineToPoint: CGPointMake(121.42, 67.83)];
        [bezier19Path addCurveToPoint: CGPointMake(101.23, 47.63) controlPoint1: CGPointMake(121.42, 56.67) controlPoint2: CGPointMake(112.38, 47.63)];
        [bezier19Path addCurveToPoint: CGPointMake(81.03, 67.83) controlPoint1: CGPointMake(90.07, 47.63) controlPoint2: CGPointMake(81.03, 56.67)];
        [bezier19Path addLineToPoint: CGPointMake(81.03, 97.77)];
        [bezier19Path addCurveToPoint: CGPointMake(60.84, 117.96) controlPoint1: CGPointMake(81.03, 108.92) controlPoint2: CGPointMake(71.99, 117.96)];
        [bezier19Path addCurveToPoint: CGPointMake(40.64, 97.77) controlPoint1: CGPointMake(49.68, 117.96) controlPoint2: CGPointMake(40.64, 108.92)];
        [bezier19Path addLineToPoint: CGPointMake(40.64, 80.88)];
        bezier19Path.lineCapStyle = kCGLineCapRound;

        bezier19Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier19Path.lineWidth = 5;
        [bezier19Path stroke];


        //// Bezier 21 Drawing
        UIBezierPath* bezier21Path = UIBezierPath.bezierPath;
        [bezier21Path moveToPoint: CGPointMake(235.9, 142.12)];
        [bezier21Path addCurveToPoint: CGPointMake(159.98, 0) controlPoint1: CGPointMake(195.64, 113.62) controlPoint2: CGPointMake(172.1, 61.17)];
        [bezier21Path addLineToPoint: CGPointMake(71.32, 0)];
        [bezier21Path addCurveToPoint: CGPointMake(0, 141.73) controlPoint1: CGPointMake(71.32, 0) controlPoint2: CGPointMake(45.58, 96.08)];
        bezier21Path.lineCapStyle = kCGLineCapRound;

        bezier21Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier21Path.lineWidth = 5;
        [bezier21Path stroke];



        CGContextRestoreGState(context);
    }


    //// Volcano Cloud
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 120.11, 330.63);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 81 Drawing
        UIBezierPath* bezier81Path = UIBezierPath.bezierPath;
        [bezier81Path moveToPoint: CGPointMake(180.59, 163.08)];
        [bezier81Path addCurveToPoint: CGPointMake(206.04, 128.98) controlPoint1: CGPointMake(193.84, 156.98) controlPoint2: CGPointMake(203.82, 144.49)];
        [bezier81Path addCurveToPoint: CGPointMake(206.3, 126.66) controlPoint1: CGPointMake(206.14, 128.2) controlPoint2: CGPointMake(206.23, 127.43)];
        [bezier81Path addCurveToPoint: CGPointMake(211.34, 127.1) controlPoint1: CGPointMake(207.95, 126.93) controlPoint2: CGPointMake(209.62, 127.1)];
        [bezier81Path addCurveToPoint: CGPointMake(242.58, 95.86) controlPoint1: CGPointMake(228.59, 127.1) controlPoint2: CGPointMake(242.58, 113.12)];
        [bezier81Path addCurveToPoint: CGPointMake(211.34, 64.63) controlPoint1: CGPointMake(242.58, 78.61) controlPoint2: CGPointMake(228.59, 64.63)];
        [bezier81Path addCurveToPoint: CGPointMake(208.07, 64.8) controlPoint1: CGPointMake(210.24, 64.63) controlPoint2: CGPointMake(209.14, 64.69)];
        [bezier81Path addCurveToPoint: CGPointMake(178.06, 31.56) controlPoint1: CGPointMake(207.41, 48.24) controlPoint2: CGPointMake(195.05, 33.99)];
        [bezier81Path addCurveToPoint: CGPointMake(155.63, 35.92) controlPoint1: CGPointMake(169.99, 30.41) controlPoint2: CGPointMake(162.19, 32.13)];
        [bezier81Path addCurveToPoint: CGPointMake(111.17, 0.57) controlPoint1: CGPointMake(148.52, 17.6) controlPoint2: CGPointMake(132, 3.55)];
        [bezier81Path addCurveToPoint: CGPointMake(55.41, 26.62) controlPoint1: CGPointMake(88.37, -2.69) controlPoint2: CGPointMake(66.82, 8.23)];
        [bezier81Path addCurveToPoint: CGPointMake(0.52, 69.8) controlPoint1: CGPointMake(28.66, 24.03) controlPoint2: CGPointMake(4.36, 42.93)];
        [bezier81Path addCurveToPoint: CGPointMake(43.42, 127.02) controlPoint1: CGPointMake(-3.44, 97.45) controlPoint2: CGPointMake(15.77, 123.07)];
        [bezier81Path addCurveToPoint: CGPointMake(71.75, 122.87) controlPoint1: CGPointMake(53.44, 128.45) controlPoint2: CGPointMake(63.19, 126.83)];
        [bezier81Path addCurveToPoint: CGPointMake(70.45, 128.52) controlPoint1: CGPointMake(71.17, 124.69) controlPoint2: CGPointMake(70.73, 126.57)];
        [bezier81Path addCurveToPoint: CGPointMake(100.16, 168.14) controlPoint1: CGPointMake(67.71, 147.67) controlPoint2: CGPointMake(81.01, 165.4)];
        [bezier81Path addCurveToPoint: CGPointMake(112.42, 167.69) controlPoint1: CGPointMake(104.36, 168.74) controlPoint2: CGPointMake(108.49, 168.53)];
        bezier81Path.lineCapStyle = kCGLineCapRound;

        bezier81Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier81Path.lineWidth = 5;
        [bezier81Path stroke];


        //// Bezier 87 Drawing
        UIBezierPath* bezier87Path = UIBezierPath.bezierPath;
        [bezier87Path moveToPoint: CGPointMake(142.25, 170.72)];
        [bezier87Path addCurveToPoint: CGPointMake(188.39, 109.66) controlPoint1: CGPointMake(145.37, 141.99) controlPoint2: CGPointMake(171.4, 115.33)];
        bezier87Path.lineCapStyle = kCGLineCapRound;

        bezier87Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier87Path.lineWidth = 5;
        [bezier87Path stroke];


        //// Bezier 89 Drawing
        UIBezierPath* bezier89Path = UIBezierPath.bezierPath;
        [bezier89Path moveToPoint: CGPointMake(128.38, 145.24)];
        [bezier89Path addCurveToPoint: CGPointMake(82.23, 84.18) controlPoint1: CGPointMake(125.25, 116.51) controlPoint2: CGPointMake(99.22, 89.85)];
        bezier89Path.lineCapStyle = kCGLineCapRound;

        bezier89Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier89Path.lineWidth = 5;
        [bezier89Path stroke];



        CGContextRestoreGState(context);
    }


    //// Cloudy Backdrop
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 214.56, 299);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 65 Drawing
        UIBezierPath* bezier65Path = UIBezierPath.bezierPath;
        [bezier65Path moveToPoint: CGPointMake(0, 97.54)];
        [bezier65Path addCurveToPoint: CGPointMake(41.91, 67.69) controlPoint1: CGPointMake(6, 80.17) controlPoint2: CGPointMake(22.5, 67.69)];
        [bezier65Path addCurveToPoint: CGPointMake(77.22, 85.21) controlPoint1: CGPointMake(56.32, 67.69) controlPoint2: CGPointMake(69.12, 74.56)];
        bezier65Path.lineCapStyle = kCGLineCapRound;

        bezier65Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier65Path.lineWidth = 5;
        [bezier65Path stroke];


        //// Bezier 67 Drawing
        UIBezierPath* bezier67Path = UIBezierPath.bezierPath;
        [bezier67Path moveToPoint: CGPointMake(250.92, 59.85)];
        [bezier67Path addCurveToPoint: CGPointMake(303.57, 27.67) controlPoint1: CGPointMake(259.29, 38.99) controlPoint2: CGPointMake(279.71, 27.67)];
        [bezier67Path addCurveToPoint: CGPointMake(348.13, 49.29) controlPoint1: CGPointMake(321.64, 27.67) controlPoint2: CGPointMake(337.74, 36.12)];
        bezier67Path.lineCapStyle = kCGLineCapRound;

        bezier67Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier67Path.lineWidth = 5;
        [bezier67Path stroke];


        //// Bezier 69 Drawing
        UIBezierPath* bezier69Path = UIBezierPath.bezierPath;
        [bezier69Path moveToPoint: CGPointMake(348.13, 49.29)];
        [bezier69Path addCurveToPoint: CGPointMake(378.1, 38.23) controlPoint1: CGPointMake(356.19, 42.39) controlPoint2: CGPointMake(366.66, 38.23)];
        [bezier69Path addCurveToPoint: CGPointMake(417.39, 60.15) controlPoint1: CGPointMake(394.71, 38.23) controlPoint2: CGPointMake(409.26, 47)];
        bezier69Path.lineCapStyle = kCGLineCapRound;

        bezier69Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier69Path.lineWidth = 5;
        [bezier69Path stroke];


        //// Bezier 71 Drawing
        UIBezierPath* bezier71Path = UIBezierPath.bezierPath;
        [bezier71Path moveToPoint: CGPointMake(78.04, 84.59)];
        [bezier71Path addCurveToPoint: CGPointMake(104.13, 55.87) controlPoint1: CGPointMake(80.83, 70.92) controlPoint2: CGPointMake(90.96, 59.91)];
        bezier71Path.lineCapStyle = kCGLineCapRound;

        bezier71Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier71Path.lineWidth = 5;
        [bezier71Path stroke];


        //// Bezier 73 Drawing
        UIBezierPath* bezier73Path = UIBezierPath.bezierPath;
        [bezier73Path moveToPoint: CGPointMake(183.66, 20.67)];
        [bezier73Path addCurveToPoint: CGPointMake(223.42, 0) controlPoint1: CGPointMake(192.52, 7.27) controlPoint2: CGPointMake(206.16, 0)];
        [bezier73Path addCurveToPoint: CGPointMake(269.79, 35.52) controlPoint1: CGPointMake(246.47, 0) controlPoint2: CGPointMake(264.28, 14.19)];
        bezier73Path.lineCapStyle = kCGLineCapRound;

        bezier73Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier73Path.lineWidth = 5;
        [bezier73Path stroke];


        //// Bezier 75 Drawing
        UIBezierPath* bezier75Path = UIBezierPath.bezierPath;
        [bezier75Path moveToPoint: CGPointMake(104.03, 55.54)];
        [bezier75Path addCurveToPoint: CGPointMake(150.55, 9.02) controlPoint1: CGPointMake(104.03, 29.85) controlPoint2: CGPointMake(124.86, 9.02)];
        [bezier75Path addCurveToPoint: CGPointMake(188.1, 28.09) controlPoint1: CGPointMake(165.97, 9.02) controlPoint2: CGPointMake(179.64, 16.53)];
        bezier75Path.lineCapStyle = kCGLineCapRound;

        bezier75Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier75Path.lineWidth = 5;
        [bezier75Path stroke];



        CGContextRestoreGState(context);
    }


    //// BG Tower
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 228.91, 359.99);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 29 Drawing
        UIBezierPath* bezier29Path = UIBezierPath.bezierPath;
        [bezier29Path moveToPoint: CGPointMake(101.77, 157.35)];
        [bezier29Path addLineToPoint: CGPointMake(130.68, 132.31)];
        [bezier29Path addLineToPoint: CGPointMake(159.6, 157.35)];
        bezier29Path.lineCapStyle = kCGLineCapRound;

        bezier29Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier29Path.lineWidth = 5;
        [bezier29Path stroke];


        //// Bezier 31 Drawing
        UIBezierPath* bezier31Path = UIBezierPath.bezierPath;
        [bezier31Path moveToPoint: CGPointMake(101.8, 157.35)];
        [bezier31Path addLineToPoint: CGPointMake(55.54, 157.35)];
        [bezier31Path addLineToPoint: CGPointMake(55.54, 226.82)];
        [bezier31Path addLineToPoint: CGPointMake(0, 226.82)];
        bezier31Path.lineCapStyle = kCGLineCapRound;

        bezier31Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier31Path.lineWidth = 5;
        [bezier31Path stroke];


        //// Bezier 33 Drawing
        UIBezierPath* bezier33Path = UIBezierPath.bezierPath;
        [bezier33Path moveToPoint: CGPointMake(179.98, 157.35)];
        [bezier33Path addLineToPoint: CGPointMake(159.6, 157.35)];
        bezier33Path.lineCapStyle = kCGLineCapRound;

        bezier33Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier33Path.lineWidth = 5;
        [bezier33Path stroke];


        //// Bezier 35 Drawing
        UIBezierPath* bezier35Path = UIBezierPath.bezierPath;
        [bezier35Path moveToPoint: CGPointMake(130.5, 24.3)];
        [bezier35Path addLineToPoint: CGPointMake(130.5, 0)];
        bezier35Path.lineCapStyle = kCGLineCapRound;

        bezier35Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier35Path.lineWidth = 5;
        [bezier35Path stroke];


        //// Bezier 37 Drawing
        UIBezierPath* bezier37Path = UIBezierPath.bezierPath;
        [bezier37Path moveToPoint: CGPointMake(159.6, 157.35)];
        [bezier37Path addLineToPoint: CGPointMake(159.6, 62.05)];
        [bezier37Path addCurveToPoint: CGPointMake(137.21, 33.89) controlPoint1: CGPointMake(159.6, 48.33) controlPoint2: CGPointMake(150.03, 36.84)];
        [bezier37Path addLineToPoint: CGPointMake(137.2, 33.93)];
        [bezier37Path addLineToPoint: CGPointMake(137.2, 24.3)];
        [bezier37Path addLineToPoint: CGPointMake(123.79, 24.3)];
        [bezier37Path addLineToPoint: CGPointMake(123.79, 33.93)];
        [bezier37Path addLineToPoint: CGPointMake(123.81, 33.98)];
        [bezier37Path addCurveToPoint: CGPointMake(101.8, 62.05) controlPoint1: CGPointMake(111.18, 37.07) controlPoint2: CGPointMake(101.8, 48.47)];
        [bezier37Path addLineToPoint: CGPointMake(101.8, 157.35)];
        bezier37Path.lineCapStyle = kCGLineCapRound;

        bezier37Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier37Path.lineWidth = 5;
        [bezier37Path stroke];


        //// Oval 2 Drawing
        UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(118.35, 61.21, 24.26, 24.26)];
        [HMToonBGStyleKit.stroke setStroke];
        oval2Path.lineWidth = 5;
        [oval2Path stroke];



        CGContextRestoreGState(context);
    }


    //// Monster
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, (monsterPosition - 111.5), 418.37);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(119.49, 138.44)];
        [bezier3Path addCurveToPoint: CGPointMake(105.93, 189.12) controlPoint1: CGPointMake(119.49, 138.44) controlPoint2: CGPointMake(102.1, 144.47)];
        [bezier3Path addCurveToPoint: CGPointMake(73.03, 259.05) controlPoint1: CGPointMake(108.96, 224.45) controlPoint2: CGPointMake(91.41, 251.22)];
        bezier3Path.lineCapStyle = kCGLineCapRound;

        bezier3Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier3Path.lineWidth = 5;
        [bezier3Path stroke];


        //// Bezier 5 Drawing
        UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
        [bezier5Path moveToPoint: CGPointMake(106.54, 208.71)];
        [bezier5Path addCurveToPoint: CGPointMake(132.31, 301.97) controlPoint1: CGPointMake(106.54, 208.71) controlPoint2: CGPointMake(152.26, 242.08)];
        bezier5Path.lineCapStyle = kCGLineCapRound;

        bezier5Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier5Path.lineWidth = 5;
        [bezier5Path stroke];


        //// Bezier 83 Drawing
        UIBezierPath* bezier83Path = UIBezierPath.bezierPath;
        [bezier83Path moveToPoint: CGPointMake(106.54, 161.76)];
        [bezier83Path addCurveToPoint: CGPointMake(147.34, 177.65) controlPoint1: CGPointMake(118.35, 178) controlPoint2: CGPointMake(147.34, 177.65)];
        [bezier83Path addLineToPoint: CGPointMake(171.7, 177.65)];
        [bezier83Path addLineToPoint: CGPointMake(171.7, 177.65)];
        [bezier83Path addCurveToPoint: CGPointMake(168.19, 195.28) controlPoint1: CGPointMake(175.28, 182.97) controlPoint2: CGPointMake(165.26, 195.25)];
        [bezier83Path addCurveToPoint: CGPointMake(193.89, 177.65) controlPoint1: CGPointMake(171.09, 195.31) controlPoint2: CGPointMake(193.47, 191.03)];
        [bezier83Path addLineToPoint: CGPointMake(193.91, 177.65)];
        [bezier83Path addCurveToPoint: CGPointMake(193.91, 177.28) controlPoint1: CGPointMake(193.91, 177.53) controlPoint2: CGPointMake(193.91, 177.4)];
        [bezier83Path addCurveToPoint: CGPointMake(173.51, 157.43) controlPoint1: CGPointMake(193.76, 166.23) controlPoint2: CGPointMake(184.56, 157.43)];
        [bezier83Path addLineToPoint: CGPointMake(161.68, 157.43)];
        [bezier83Path addCurveToPoint: CGPointMake(130.04, 101.02) controlPoint1: CGPointMake(130.56, 157.43) controlPoint2: CGPointMake(130.04, 101.02)];
        bezier83Path.lineCapStyle = kCGLineCapRound;

        bezier83Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier83Path.lineWidth = 5;
        [bezier83Path stroke];


        //// Bezier 85 Drawing
        UIBezierPath* bezier85Path = UIBezierPath.bezierPath;
        [bezier85Path moveToPoint: CGPointMake(19.87, 174.58)];
        [bezier85Path addLineToPoint: CGPointMake(57.11, 174.58)];
        [bezier85Path addCurveToPoint: CGPointMake(53.6, 192.2) controlPoint1: CGPointMake(60.69, 179.9) controlPoint2: CGPointMake(50.67, 192.18)];
        [bezier85Path addCurveToPoint: CGPointMake(79.3, 174.58) controlPoint1: CGPointMake(56.5, 192.23) controlPoint2: CGPointMake(86.46, 192.2)];
        [bezier85Path addCurveToPoint: CGPointMake(35.39, 144.22) controlPoint1: CGPointMake(72.45, 156.27) controlPoint2: CGPointMake(54.94, 144.16)];
        bezier85Path.lineCapStyle = kCGLineCapRound;

        bezier85Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier85Path.lineWidth = 5;
        [bezier85Path stroke];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(0, 71.32)];
        [bezier2Path addLineToPoint: CGPointMake(16, 47.32)];
        [bezier2Path addLineToPoint: CGPointMake(36, 57.32)];
        [bezier2Path addLineToPoint: CGPointMake(46, 35.32)];
        [bezier2Path addLineToPoint: CGPointMake(71, 41.32)];
        [bezier2Path addLineToPoint: CGPointMake(82, 19.32)];
        [bezier2Path addLineToPoint: CGPointMake(105, 24.32)];
        [HMToonBGStyleKit.stroke setStroke];
        bezier2Path.lineWidth = 5;
        [bezier2Path stroke];


        //// Head Top
        {
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 104.17, 23.5);
            CGContextRotateCTM(context, -monsterJawTop * M_PI / 180);



            //// Eye Drawing
            UIBezierPath* eyePath = UIBezierPath.bezierPath;
            [eyePath moveToPoint: CGPointMake(48.21, 5.09)];
            [eyePath addLineToPoint: CGPointMake(30.94, 3.93)];
            eyePath.lineCapStyle = kCGLineCapRound;

            eyePath.lineJoinStyle = kCGLineJoinRound;

            [HMToonBGStyleKit.stroke setStroke];
            eyePath.lineWidth = 5;
            [eyePath stroke];


            //// Jaw Top Drawing
            CGContextSaveGState(context);

            UIBezierPath* jawTopPath = UIBezierPath.bezierPath;
            [jawTopPath moveToPoint: CGPointMake(45.37, 31.44)];
            [jawTopPath addLineToPoint: CGPointMake(59.51, 30.81)];
            [jawTopPath addLineToPoint: CGPointMake(64.04, 17.4)];
            [jawTopPath addLineToPoint: CGPointMake(78.19, 16.77)];
            [jawTopPath addLineToPoint: CGPointMake(82.71, 3.35)];
            [jawTopPath addLineToPoint: CGPointMake(96.86, 2.72)];
            [jawTopPath addLineToPoint: CGPointMake(101.4, -10.7)];
            [jawTopPath addCurveToPoint: CGPointMake(0.5, 0.38) controlPoint1: CGPointMake(77.93, -27.34) controlPoint2: CGPointMake(43.54, -31.64)];
            [jawTopPath moveToPoint: CGPointMake(0.5, 0.38)];
            [jawTopPath addLineToPoint: CGPointMake(0.83, 0.82)];
            jawTopPath.lineCapStyle = kCGLineCapRound;

            jawTopPath.lineJoinStyle = kCGLineJoinRound;

            [HMToonBGStyleKit.stroke setStroke];
            jawTopPath.lineWidth = 5;
            [jawTopPath stroke];

            CGContextRestoreGState(context);



            CGContextRestoreGState(context);
        }


        //// Head Bottom
        {
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 130.04, 101.29);
            CGContextRotateCTM(context, -monsterJawBottom * M_PI / 180);



            //// Bezier 79 Drawing
            CGContextSaveGState(context);
            CGContextTranslateCTM(context, 42.21, -37.57);
            CGContextScaleCTM(context, tongue, 1);

            UIBezierPath* bezier79Path = UIBezierPath.bezierPath;
            [bezier79Path moveToPoint: CGPointMake(0, 0)];
            [bezier79Path addCurveToPoint: CGPointMake(46.58, -14.45) controlPoint1: CGPointMake(8.69, -28.76) controlPoint2: CGPointMake(31.6, 4.96)];
            bezier79Path.lineCapStyle = kCGLineCapRound;

            bezier79Path.lineJoinStyle = kCGLineJoinRound;

            [HMToonBGStyleKit.stroke setStroke];
            bezier79Path.lineWidth = 5;
            [bezier79Path stroke];

            CGContextRestoreGState(context);


            //// Bezier 4 Drawing
            UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
            [bezier4Path moveToPoint: CGPointMake(0, -0.27)];
            [bezier4Path addCurveToPoint: CGPointMake(68.8, -31.59) controlPoint1: CGPointMake(0, -0.27) controlPoint2: CGPointMake(49.46, 5.04)];
            [bezier4Path addCurveToPoint: CGPointMake(19.5, -32.61) controlPoint1: CGPointMake(68.8, -31.59) controlPoint2: CGPointMake(48.22, -40.73)];
            [HMToonBGStyleKit.stroke setStroke];
            bezier4Path.lineWidth = 5;
            [bezier4Path stroke];



            CGContextRestoreGState(context);
        }



        CGContextRestoreGState(context);
    }


    //// Left Building
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, -22, 387.53);
        CGContextScaleCTM(context, 0.5, 0.5);



        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(0, 0)];
        [bezierPath addLineToPoint: CGPointMake(96, 0)];
        [bezierPath addLineToPoint: CGPointMake(96, 41)];
        [bezierPath addLineToPoint: CGPointMake(123, 41)];
        [bezierPath addLineToPoint: CGPointMake(123, 163)];
        [bezierPath addLineToPoint: CGPointMake(141, 163)];
        [bezierPath addLineToPoint: CGPointMake(141, 466)];
        [bezierPath addLineToPoint: CGPointMake(0, 466)];
        [bezierPath addLineToPoint: CGPointMake(0, 0)];
        [HMToonBGStyleKit.fill setFill];
        [bezierPath fill];


        //// Bezier 9 Drawing
        UIBezierPath* bezier9Path = UIBezierPath.bezierPath;
        [bezier9Path moveToPoint: CGPointMake(141.36, 313.02)];
        [bezier9Path addLineToPoint: CGPointMake(141.36, 164.01)];
        [bezier9Path addLineToPoint: CGPointMake(123.36, 164.01)];
        [bezier9Path addLineToPoint: CGPointMake(123.36, 40.75)];
        [bezier9Path addLineToPoint: CGPointMake(96.11, 40.7)];
        [bezier9Path addLineToPoint: CGPointMake(96.11, 1.08)];
        [bezier9Path addLineToPoint: CGPointMake(1, 1.08)];
        bezier9Path.lineCapStyle = kCGLineCapRound;

        bezier9Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier9Path.lineWidth = 5;
        [bezier9Path stroke];


        //// Bezier 11 Drawing
        UIBezierPath* bezier11Path = UIBezierPath.bezierPath;
        [bezier11Path moveToPoint: CGPointMake(40.27, 138.49)];
        [bezier11Path addLineToPoint: CGPointMake(97.13, 138.49)];
        [bezier11Path addLineToPoint: CGPointMake(97.13, 155.72)];
        [bezier11Path addLineToPoint: CGPointMake(40.27, 155.72)];
        bezier11Path.lineCapStyle = kCGLineCapRound;

        bezier11Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier11Path.lineWidth = 5;
        [bezier11Path stroke];


        //// Bezier 13 Drawing
        UIBezierPath* bezier13Path = UIBezierPath.bezierPath;
        [bezier13Path moveToPoint: CGPointMake(40.27, 106.95)];
        [bezier13Path addLineToPoint: CGPointMake(97.13, 106.95)];
        [bezier13Path addLineToPoint: CGPointMake(97.13, 124.18)];
        [bezier13Path addLineToPoint: CGPointMake(40.27, 124.18)];
        bezier13Path.lineCapStyle = kCGLineCapRound;

        bezier13Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier13Path.lineWidth = 5;
        [bezier13Path stroke];


        //// Bezier 15 Drawing
        UIBezierPath* bezier15Path = UIBezierPath.bezierPath;
        [bezier15Path moveToPoint: CGPointMake(40.27, 75.41)];
        [bezier15Path addLineToPoint: CGPointMake(97.13, 75.41)];
        [bezier15Path addLineToPoint: CGPointMake(97.13, 92.64)];
        [bezier15Path addLineToPoint: CGPointMake(40.27, 92.64)];
        bezier15Path.lineCapStyle = kCGLineCapRound;

        bezier15Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier15Path.lineWidth = 5;
        [bezier15Path stroke];


        //// Bezier 17 Drawing
        UIBezierPath* bezier17Path = UIBezierPath.bezierPath;
        [bezier17Path moveToPoint: CGPointMake(96.11, 40.7)];
        [bezier17Path addLineToPoint: CGPointMake(77.04, 40.7)];
        bezier17Path.lineCapStyle = kCGLineCapRound;

        bezier17Path.lineJoinStyle = kCGLineJoinRound;

        [HMToonBGStyleKit.stroke setStroke];
        bezier17Path.lineWidth = 5;
        [bezier17Path stroke];



        CGContextRestoreGState(context);
    }
}

@end
