//
//  HMToonBGStyleKit.h
//  Homage App
//
//  Created by Aviv Wolf on 10/23/14.
//  Copyright (c) 2014 Homage. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HMToonBGStyleKit : NSObject

// Colors
+ (UIColor*)fill;
+ (UIColor*)stroke;

// Drawing Methods
+ (void)drawCanvas1WithMonsterPosition: (CGFloat)monsterPosition monsterRoarFraction: (CGFloat)monsterRoarFraction;

@end
